---
users:
  - name: ubuntu
    system: no
    shell: /bin/bash
    key: https://github.com/prakashsurya.keys

vault_version: 0.6.1
vault_checksum: 4f248214e4e71da68a166de60cc0c1485b194f4a2197da641187b745c8d5b8be

zfs_vdevs:
  - xvdb
  - xvdc
  - xvdd

docker_users:
 - ubuntu
