---
- name: assert supported distribution
  assert:
    that:
      - ansible_distribution == 'Ubuntu'

- name: install ZFS package
  apt:
    name: zfs
    state: present

#
# When running this on EC2 disks that haven't been previously modified,
# the disks will lack any EFI label. As a result, when "zpool create"
# is run, it will fail. To workaround this issue, we have to use the
# "-f" option; this is obviously dangerous since we may clobber existing
# data if we happened to get the "zfs_vdevs" variable wrong, so we need
# to be extra careful with that variable.
#
- name: create ZFS pool
  command: zpool create -f zfs {{ zfs_vdevs | join(' ') }}
  args:
    creates: /zfs
  when: zfs_vdevs is defined

- name: configure zfs dataset properties
  zfs:
    name: zfs
    state: present
    mountpoint: /zfs
    canmount: on
    checksum: sha256
    compression: lz4
