---
#
# We must specify the version of "docker-py" explicitly to workaround
# this ansible issue: https://github.com/ansible/ansible/issues/17495
#
dependencies:
  - { role: angstwad.docker_ubuntu, pip_version_docker_py: 1.9.0 }
